{
 "title": "wan1",
 "tags": [ "wan" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Live Endpoints (mkp)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_LiveTargetEndpointCount{instance=\"localhost:8091\",tag=\"WanDiscovery-mkp\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "Dead Endpoints (mkp)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_DeadTargetEndpointCount{instance=\"localhost:8091\",tag=\"WanDiscovery-mkp\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "All Endpoints (mkp)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_TargetEndpointCount{instance=\"localhost:8091\",tag=\"WanDiscovery-mkp\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "WAN Outbound Queue Size (mkp)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_outboundQueueSize{exported_instance=\"_hzInstance_1_wan1\", tag0=\"\\\"publisherId=location2-mkp\\\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAN Endpoints (mkp)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_DeadTargetEndpointCount{instance=\"localhost:8091\", tag=\"WanDiscovery-mkp\"}",
     "legendFormat": "Dead"
    },
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_LiveTargetEndpointCount{instance=\"localhost:8091\", tag=\"WanDiscovery-mkp\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_TargetEndpointCount{instance=\"localhost:8091\", tag=\"WanDiscovery-mkp\"}",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "WAN Endpoints (mkp)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_DeadTargetEndpointCount{instance=\"localhost:8091\", tag=\"WanDiscovery-mkp\"}",
     "legendFormat": "Dead"
    },
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_LiveTargetEndpointCount{instance=\"localhost:8091\", tag=\"WanDiscovery-mkp\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_TargetEndpointCount{instance=\"localhost:8091\", tag=\"WanDiscovery-mkp\"}",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Live Endpoints (mkq)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_LiveTargetEndpointCount{instance=\"localhost:8091\",tag=\"WanDiscovery-mkq\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "Dead Endpoints (mkq)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_DeadTargetEndpointCount{instance=\"localhost:8091\",tag=\"WanDiscovery-mkq\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "All Endpoints (mkq)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_TargetEndpointCount{instance=\"localhost:8091\",tag=\"WanDiscovery-mkq\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "WAN Outbound Queue Size (mkq)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_outboundQueueSize{exported_instance=\"_hzInstance_1_wan1\", tag0=\"\\\"publisherId=location2-mkq\\\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Put Test (mkq)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_mkq_1_localTotalPutLatency{exported_instance=\"_hzInstance_1_wan1\"}/com_hazelcast_mkq_1_localPutOperationCount{exported_instance=\"_hzInstance_1_wan1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAN Endpoints (mkq)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_DeadTargetEndpointCount{instance=\"localhost:8091\", tag=\"WanDiscovery-mkq\"}",
     "legendFormat": "Dead"
    },
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_LiveTargetEndpointCount{instance=\"localhost:8091\", tag=\"WanDiscovery-mkq\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_TargetEndpointCount{instance=\"localhost:8091\", tag=\"WanDiscovery-mkq\"}",
     "legendFormat": "All"
    }
   ]
  }
 ]
}