#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2022 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Start Hazelcast CLI console

SYNOPSIS
   $EXECUTABLE [-?]

DESCRIPTION
   Starts Hazelcast CLI console.

EXAMPLES
   # Ingest entries to the relevant maps using String keys
   @console-relevant.txt

   # Ingest a session entry to the primary map
   @console-primary.txt

   # Destroy the primary and relevant maps
   @console-destroy.txt
   
EOF
exit
fi

# Export LOG_FILE (See etc/log4j2.properties)
if [[ ${OS_NAME} == CYGWIN* ]]; then
   export LOG_FILE=$LOG_DIR\\$EXECUTABLE.log
   CLASSPATH="$(cygpath -wp "$CLASSPATH")"
else
   export LOG_FILE=$LOG_DIR/$EXECUTABLE.log
fi

# Application executable name. Useful for displaying usage.
export JAVA_OPTS="$JAVA_OPTS -Dexecutable.name=$EXECUTABLE"

if [ $HAZELCAST_MAJOR_VERSION_NUMBER -eq 5 ]; then
   hz-cli --config $HAZELCAST_CLIENT_CONFIG_FILE console
else
   console.sh
fi
