#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./$EXECUTABLE [-folder <folder-name>] [-?]"
   echo ""
   echo "   Clears all Prometheus series. This command is useful if you want to remove all old data and"
   echo "   start fresh. To run this command, you must run Prometheus with the '--web.enable-admin-api'"
   echo "   option as shown in the example below."
   echo ""
   echo "   prometheus --web.enable-admin-api --config.file=etc/prom-hazelcast.yml"
   echo ""
   echo "Default: ./$EXECUTABLE"
   echo ""
   exit
fi

curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={_name__=~".+"}'
curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/clean_tombstones'
