{
 "title": "wan2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SessionExpirationService Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "com_hazelcast_SessionExpirationService_QueueSize{exported_instance=\"_hzInstance_1_wan2\"}"
    }
   ]
  },
  {
   "title": "WAN: Live Endpoints",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_LiveTargetEndpointCount{instance=\"localhost:8191\",tag=\"WanDiscovery\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "WAN: Dead Endpoints",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_DeadTargetEndpointCount{instance=\"localhost:8191\",tag=\"WanDiscovery\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "WAN: All Endpoints",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_TargetEndpointCount{instance=\"localhost:8191\",tag=\"WanDiscovery\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "WAN: Outbound Queue Size",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_outboundQueueSize{exported_instance=\"_hzInstance_1_wan2\", tag0=\"\\\"publisherId=location1\\\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAN: Endpoints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_DeadTargetEndpointCount{instance=\"localhost:8191\", tag=\"WanDiscovery\"}",
     "legendFormat": "Dead"
    },
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_LiveTargetEndpointCount{instance=\"localhost:8191\", tag=\"WanDiscovery\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_TargetEndpointCount{instance=\"localhost:8191\", tag=\"WanDiscovery\"}",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "WAN: Endpoints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_DeadTargetEndpointCount{instance=\"localhost:8191\", tag=\"WanDiscovery\"}",
     "legendFormat": "Dead"
    },
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_LiveTargetEndpointCount{instance=\"localhost:8191\", tag=\"WanDiscovery\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "org_hazelcast_addon_IpDiscoveryStatus_TargetEndpointCount{instance=\"localhost:8191\", tag=\"WanDiscovery\"}",
     "legendFormat": "All"
    }
   ]
  }
 ]
}